-- Database schema for FarmInvest Lite

CREATE DATABASE IF NOT EXISTS farminvest;
USE farminvest;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS investments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  farmer_name VARCHAR(255) NOT NULL,
  crop VARCHAR(255) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_investments_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE SET NULL
);
